meta_product_name: "Captain Cocktail"
meta_title: "Captain Cocktail | Create your Cocktail library"
meta_description: "Get inspiration from our famous cocktail recipes and create your owns cocktails. Access anytimes to your cocktails private library! You can add cocktail, edit it and add ingredients!"
meta_image: "cover.png"
twitter_account: "@product_twitter_account"
